### ISSUE TITLE
login or authenticate failed: unauthorized!

### ISSUE THREAD

**Issue by philou155** [zohead/kuaipan-chromeos#1]
I could login and it was working for a while but now i get this error message when i click mount kuaipan:

login or authenticate failed: unauthorized!

nothing i can do. i uninstalled and reinstalled the app but same result

**Comment by zohead** [comment]
When you click mount Kuaipan button, does a new window popuped and require you to enter username/password to login/grant permission?

You can go to Chrome extensions page, start this App, click "view.html" in extensions page to open Developer Tools, then mount again, you will see some debug message in console, also you can check network request results.

I will check this on my chromebook after I go home. ^_^

**Comment by philou155** [comment]
No, that's the problem.... thanks for the answer.

here's what i get in the console:

https://openapi.kuaipan.cn/open/requestToken?oauth_consumer_key=xcfKeHVF519…d.chromiumapp.org%2Fkuaipan&oauth_signature=nfGhvcMGoIfqNozPzBztan5YwfU%3D Failed to load resource: the server responded with a status of 401 (Unauthorized)

https://openapi.kuaipan.cn/open/requestToken?oauth_consumer_key=xcfKeHVF519…d.chromiumapp.org%2Fkuaipan&oauth_signature=FJTLBOnWbWfh7CYfzK8jD0cUcDU%3D Failed to load resource: the server responded with a status of 401 (Unauthorized)
jquery-2.1.3.min.js:4 

GET https://openapi.kuaipan.cn/open/requestToken?oauth_consumer_key=xcfKeHVF519…d.chromiumapp.org%2Fkuaipan&oauth_signature=DLMZfK51g5k714j4dGQAA0pP7wk%3D 401 (Unauthorized)

**Comment by zohead** [comment]
I have test this on my Chromebook, login works fine.
BTW:
You can check your Chromebook's date & time, it should not be later or earlier more than 5 minutes with the standard time.
Can you sync Chromebook with some NTP server then try again?

**Comment by philou155** [comment]
it works now... yeah, might have been the date and time thing

**Comment by zohead** [comment]
Great, I should put this in error message, tell user to check system time if unauthorized happens.
